### ISSUE TITLE
Is possible to set global table prefix?

### ISSUE THREAD

**Issue by PayteR** [remp2020/crm-skeleton#7]
Hi, i want to set a global prefix for all remp tables. I want to use remp with other apps on the same database, but there are lot of tables and it's messy. 

I see that migration of tables is made by https://phinx.org/ and table names are hardcoded there, so this is not easy. 

In application is used Nette database layer, and i don't see this option in there, but in remp is repository pattern used, and is theoretically possible to add table prefix from config in getTable() method here https://github.com/remp2020/crm-application-module/blob/master/src/model/Repository/Repository.php#L40.

My proposal is to not change migrations for now (maybe later) and manually change table names in the database.  Next, add that prefix variable in getTable() and use these tables with a prefix. Is there any obstacle that i need to consider? If not i could prepare PR for this. What do you think?

**Comment by rootpd** [comment]
Hi, there are two issues that unfortunately won't allow this in the CRM, one of them is technical and one of them considers security. 

- There are places in the code where we need to build query manually due to performance reasons. This is both in open-source version and in internal modules that we (and other publishers) use. Also the whole `SegmentsModule` is based on a query generation and would be hugely affected. This would be a breaking change that would require non-small amount of work by multiple publishers before updating CRM to the next version.

  As there's really no need for prefixing feature, I don't think it would justify the cost of the changes. (I'm comparing all the work described above vs. creating new empty database on your DB server). And even though we're not on v1.0 yet, we shouldn't aim for breaking changes like this unless there's really need to do them or the gain outperforms costs.

- The other concern I have is a security. If you host multiple Wordpress instances on one database it might be OK - WP is expected to be run on limited hostings with one database - but I don't really see a reason why multiple different applications should be actually hosted within the same database.

  Not only the other applications can accidentally read/delete CRM's records, but you have no control on access-level permissions. Basically everybody could see and alter everything which is something we don't want to embrace.

Hope it makes sense.

**Comment by PayteR** [comment]
Then create a new env variable CRM_DB_PREFIX and add it everywhere where it's needed, even in custom DB queries. Backward compatibility will be preserved, because default value will be a blank string. What do you think?

**Comment by rootpd** [comment]
It's not just about backward compatibility. When such feature is present in the system, it already needs to be handled by all open-sourced/internal modules in case someone is doing clean install with prefix. 

Once the prefix is part of the configuration, you need to work with an idea that people are actively using it (because they can set itin the `.env` file) and deliver the expectation that clean installation will work as if there was no prefix. Using new ENV variable doesn't make the amount of work any different, it still all needs to be done at the same time. 

Unfortunately the amount of work and testing for such change cannot be justified at this point (against creating a new database).

**Comment by PayteR** [comment]
Ok, what about to not include this variable in .env.example so it will be hidden variable and will be used only by devs that are aware of this feature?

**Comment by rootpd** [comment]
This is still just circumventing around "how to get it in" and not considering the amount of work to support it (both now and in the future). It's either undocumented and nobody should depend on it or it's documented and it should be available for everyone. There shouldn't be a grey area.

I think the reasons why this is not something we want to support right now were explained fully enough already.
